services:
  - type: web
    name: shopping-list
    env: node
    plan: free
    buildCommand: yarn install; yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
